site_name: Kitodo Production using OCR-D

nav:
  - Intro: 'index.md'
  - Services: '*include ./_modules/*/mkdocs.yml'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    primary: white
    accent: blue
