site_name: Kitodo Production using OCR-D

nav:
  - Intro: 'index.md'
  - Installation: 
    - 'installation/'
  - Usage: 'usage'
    - 'usage/'
  - Services: '*include ./_modules/*/mkdocs.yml'

plugins:
  - monorepo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    primary: white
    accent: blue
