site_name: Kitodo.Production using OCR-D

nav:
  - Home: 'index.md'
  - 'Getting Started': 'getting-started.md'
  - Setup:
    - Prerequisites: 'setup/prerequisites.md'
    - Configuration: 'setup/configuration.md'
        - 'Environment Variables of Docker Compose': 'setup/configuration/environment-variables.md'
        - 'Makefile Variables': 'setup/configuration/makefile.md'
    - Preparation: 'setup/preparation.md'
  - Usage: 'usage/handling.md'
      - Services:
        - Kitodo.Production: 'usage/services/kitodo-production.md'
        - OCR-D Monitor: 'usage/services/ocrd-monitor.md'
  - Modules: '*include ./_modules/*/mkdocs.yml'

plugins:
  - monorepo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    primary: white
    accent: blue
