site_name: Kitodo Production using OCR-D

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    primary: white
    accent: blue
