name: ci 
on:
  push:
    branches:
      - mkdocs-material      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build environment variable markdown files
        run: ./.github/scripts/build-env-mds.sh
        shell: bash
      - run: pip install mkdocs-material
      - run: pip install mkdocs-monorepo-plugin
      - run: mkdocs build --theme material
      - run: mkdocs gh-deploy --force